### ISSUE TITLE
[Feature Request] Allow changing the favourite team dynamically

### ISSUE THREAD

**Issue by shivangc22** [KieronQuinn/SmartspacerPlugins#1]
### Select the Plugin you are requesting for

Yahoo! Sport

### Request

Currently to change the team shown in the target, it has to be done through opening the plugin settings in smartspacer. If possible, please add an option to change this dynamically, either through clicking on the target, or through Tasker

**Comment by shivangc22** [comment]
On my device it does not open the Yahoo app, it does nothing at all when clicked.
And I have tried adding multiple targets, however for some teams it shows the previous matches (last night's UCL games, for Chelsea it shows Chelsea vs Arsenal on 21), however for other teams, like Barcelona, Milan etc the target does not appear at all.

**Comment by shivangc22** [comment]
Is it possible to add something like the yahoo sport large widget (native one)? Because in it you can add all the teams you want and there are arrow buttons to navigate through teams. 
Obviously the same cannot be implemented through smartspacer but something similar that allows navigating through all your favourite teams, just like the Yahoo Sport Large widget.

**Comment by KieronQuinn** [comment]
No, like I said the way to do this in Smartspacer is to just add multiple Targets. Even if I did implement it from the paged Yahoo widget, it would still work in exactly the same way with games only showing while active. 

If you want full widget functionality, all the time, I suggest you just stick to the actual widget.

**Comment by shivangc22** [comment]
Alright, thank you.
