### ISSUE TITLE
[Plugin Request] Unread messages from K-9 Mail

### ISSUE THREAD

**Issue by shivangc22** [KieronQuinn/SmartspacerPlugins#10]
### App / Plugin Name

K-9 Mail

### URL

https://k9mail.app/

### Description

K-9 is a FOSS email client and alternative to Gmail.
The plugin should fetch the number of unread messages from K-9 (for a particular account or all added emails) and display it in a complication, similar to the gmail unread complication.
K-9 Mail has a widget that exposes the same data, for either a particular account, or all the accounts added in the app.

### Where will the plugin get data from?

Widget

### Requirements

- [X] I have read the requirements
- [X] The information I have provided is correct

**Comment by KieronQuinn** [comment]
Added in Notification plugin v1.1
