### ISSUE TITLE
[Bug] Amazon Plugin

### ISSUE THREAD

**Issue by ElderHallow** [KieronQuinn/SmartspacerPlugins#11]
### Select the Plugin you are reporting for

Amazon

### Description

Hi! Sorry about posting the bug report in the wrong place. I'm new to doing this in GitHub.

I have the Amazon Plugin installed. On my home screen it asks me to sign in. But in the app itself it's says I am signed in. Am doing something wrong or is this a bug. Please see screenshots:

![Screenshot_20231105-093937](https://github.com/KieronQuinn/SmartspacerPlugins/assets/83273463/7d0cb331-44f8-45e2-ac47-ad2d9b9267c0)
![Screenshot_20231105-094417](https://github.com/KieronQuinn/SmartspacerPlugins/assets/83273463/8f0d3b5e-d387-49a3-926d-494dc9be78e5)
![Screenshot_20231105-094423](https://github.com/KieronQuinn/SmartspacerPlugins/assets/83273463/b5998d83-7e8b-4b5a-bcaa-94db410b9b9e)
![Screenshot_20231105-094556](https://github.com/KieronQuinn/SmartspacerPlugins/assets/83273463/4f646be8-0de3-4e8d-bdf5-9ad7032b0b67)

Pixel 5 Android 14. Thanks.

**Comment by KieronQuinn** [comment]
Forgot to close this, this will have been fixed in the 2.0 Amazon plugin update with the rewrite.
