### ISSUE TITLE
[Bug] Health Connect complications not refreshing 

### ISSUE THREAD

**Issue by silverman10** [KieronQuinn/SmartspacerPlugins#12]
### Select the Plugin you are reporting for

Health Connect

### Description

have a couple of HealthConnect complications on the lock screen. The stats on the lock screen doesn't refresh every 5 mins(interval set to 5 mins). As soon as the stat is force refreshed, I can see it on the lock screen.

On a Pixel 7 pro, running Android 14 and latest versions of everything.

**Comment by KieronQuinn** [comment]
Most apps that push to Health Connect don't push that often, some are only updated every hour or more, certainly not 5 minutes. Which app and metric are you using? Can you send a screenshot of Health Connect's settings showing the metric has definitely been updated in that time, and isn't showing in Smartspacer after 5 minutes?

**Comment by silverman10** [comment]
Health Connect is definitely updated, as I have checked Smartspacer in the said intervals and the fact that it updates immediately after i refresh the stat from within the settings. 

I'll try this again in a controlled environment and get back to you with some screenshots and recordings if possible

**Comment by silverman10** [comment]
It's decided to work now, I can see the stats updated. A reboot might have helped I think. 

Thanks. And awesome job with this!
