### ISSUE TITLE
[Bug] battery plugin stops recognizing my headphones after some time

### ISSUE THREAD

**Issue by Giggigx** [KieronQuinn/SmartspacerPlugins#13]
### Select the Plugin you are reporting for

Battery

### Description

The complicaton randomly stops showing, when checking the list of connected devices my headphones stop showing up, even though they're connected. Power cycling the headphones solves the issue.

I initially thought that maybe it was being killed by android's power management so I set the plugin as unrestricted, but the issue remains.
![Screenshot_20231109-101323](https://github.com/KieronQuinn/SmartspacerPlugins/assets/38881699/c234909e-b3ce-474d-8e83-ce59e5b1f9ab)
![Screenshot_20231109-101330](https://github.com/KieronQuinn/SmartspacerPlugins/assets/38881699/de466699-bd0f-4b7c-8666-972297633eb3)

**Comment by KieronQuinn** [comment]
So after some debugging, I've found the actual issue causing this lies in the Battery widget, which sometimes loses a device. 

I've countered this by adding caching, which shows the last known level of the device. Usually this is pretty accurate, and it will update itself when the level next shows up in the widget, but obviously it causes another problem, in that it continues to show the last known level for a disconnected device.

I'm going to work around this by adding a bluetooth device connected requirement to Smartspacer itself, so you can use this new option and the new requirement to show the previous known value but only when the device is actually connected (regardless of what the Battery widget thinks). 

I'm going to hold off updating the plugin until the Smartspacer update is done though.

**Comment by KieronQuinn** [comment]
This is now merged and included in Battery v1.1 and Smartspacer v1.5

**Comment by Giggigx** [comment]
Thank you for fixing this, also I love the phone battery percentage feature
