### ISSUE TITLE
[Feature Request] individual app screen time

### ISSUE THREAD

**Issue by fillwithjoy1** [KieronQuinn/SmartspacerPlugins#14]
### Select the Plugin you are requesting for

Aftership

### Request

Can you update the screen time digital well being complication to include the ability for us to monitor a specific app screen time and read how much time we have if we set a screen time limit on it. Thanks

**Comment by KieronQuinn** [comment]
I think you selected the wrong plugin, but this isn't possible for Digital Wellbeing. The widget is the only source of data and it doesn't allow this.

**Comment by fillwithjoy1** [comment]
Understandable, have a good day.
