### ISSUE TITLE
TickTick [Plugin Request] 

### ISSUE THREAD

**Issue by adadoukis** [KieronQuinn/SmartspacerPlugins#17]
### App / Plugin Name

TickTick

### Description

Offer integration with TickTick to show the next upcoming event (similar to the calendar intergration)

### Where will the plugin get data from?

Other (please specify in the description)

### Requirements

- [X] I have read the requirements
- [X] The information I have provided is correct

**Comment by KieronQuinn** [comment]
You have not provided a data source, which is required. Please specify where the data will come from in a new issue.
