### ISSUE TITLE
Tasker target takes long to become visible [Bug] 

### ISSUE THREAD

**Issue by eliasacab** [KieronQuinn/SmartspacerPlugins#19]
### Select the Plugin you are reporting for

Tasker

### Description

Toggling on the Tasker target visibility with a task often has a long delay (not always).

I have a task that enables the target when I connect my bluetooth earbuds and it also does a bunch of other things. The rest of the items in the task work as expected, but the Target Visibility action often takes almost a minute to go into effect (as in, the target doesn't become visible until after a while), even though it's at the top of the list of actions.

Is this a smartspace limitation? I have enabled "update when not visible", but that didn't help either. Thanks!

**Comment by KieronQuinn** [comment]
I can't reproduce this, so I guess you're seeing some sort of occasional delay in the system which is out of my control unfortunately.
