### ISSUE TITLE
Tap Action Without Unlocking [Feature Request] 

### ISSUE THREAD

**Issue by eliasacab** [KieronQuinn/SmartspacerPlugins#2]
### Select the Plugin you are requesting for

Tasker

### Request

Thanks for this powerful app, especially with Tasker integration!

Is it possible at all to use the Tasker target Tap Action without needing to unlock the device? So I can tap the Tasker target and update it from the lockscreen. Thanks!

**Comment by KieronQuinn** [comment]
Added to the Tasker Plugin in 1.0.5
