### ISSUE TITLE
[Feature Request] Google Voice for notification plugin

### ISSUE THREAD

**Issue by ThatOneCalculator** [KieronQuinn/SmartspacerPlugins#24]
### Select the Plugin you are requesting for

Notifications

### Request

Notification counts for Google Voice (has widget)

![Screenshot_20231210-104014~2.png](https://github.com/KieronQuinn/SmartspacerPlugins/assets/44733677/58066daa-7d61-4238-800d-820004ffba1e)

**Comment by KieronQuinn** [comment]
They need to have a widget which displays the unread count, or support for the old badge system. I know for a fact Discord has neither of these, please specify and/or remove those which can actually do this, otherwise I'll have to close it.

**Comment by ThatOneCalculator** [comment]
Gotcha. Is there a way to check if an app supports the old badge system?

**Comment by KieronQuinn** [comment]
> Gotcha. Is there a way to check if an app supports the old badge system?

For the open source ones, check if they use a library like [this one](https://github.com/arturogutierrez/Badges). Otherwise, only by decompiling the APKs and checking. 

Aliucord doesn't work, so you can remove that one too.

**Comment by ThatOneCalculator** [comment]
Seems that Google Voice is the only viable option for now. I'll check on Milktea in a bit since it's open source, and it uses some older components iirc (unlike the other apps I listed)

**Comment by KieronQuinn** [comment]
@ThatOneCalculator Can you try this APK and see if it works for Google Voice? It's not available in the UK so I cannot test it

[notifications-release.zip](https://github.com/KieronQuinn/SmartspacerPlugins/files/13757055/notifications-release.zip)

**Comment by ThatOneCalculator** [comment]
Doesn't seem to work. I have two unread texts on Google Voice, but they don't show up.

**Comment by KieronQuinn** [comment]
You'll need to provide a layout inspector dump of the widget then since I cannot add it

**Comment by ThatOneCalculator** [comment]
@KieronQuinn DM'd it to you on Discord since it contains my phone number.

**Comment by KieronQuinn** [comment]
Added in Notification plugin v1.1
