### ISSUE TITLE
[Bug] Notifications plugin doesn't work with Nekogram

### ISSUE THREAD

**Issue by ThatOneCalculator** [KieronQuinn/SmartspacerPlugins#25]
### Select the Plugin you are reporting for

Notifications

### Description

While Telegram forks are apparently supported, it doesn't seem to work with Nekogram, as it gives the error "The Widget required for this Complication is unavailable" (despite Nekogram having the regular Telegram widgets)

![Screenshot_20231210-102026](https://github.com/KieronQuinn/SmartspacerPlugins/assets/44733677/b1c0f924-b231-434d-8a2f-8d35e43c3f81)

**Comment by KieronQuinn** [comment]
This has previously been reported and is an issue with Nekogram, not Smartspacer. If it cannot access the widget, the plugin cannot work.
