### ISSUE TITLE
Health Connect abbreviates miles as 'm' instead of 'mi'

### ISSUE THREAD

**Issue by ThatOneCalculator** [KieronQuinn/SmartspacerPlugins#27]
### Select the Plugin you are reporting for

Health Connect

### Description

The distance complication for the Health Connect plugin says '2.3m' when it should be '2.3 mi', since 'm' is the abbreviation for meters. 

![Screenshot_20231212-104958~2](https://github.com/KieronQuinn/SmartspacerPlugins/assets/44733677/41630973-5231-40a5-8525-d44005bd1558)
![Screenshot_20231212-104940~2](https://github.com/KieronQuinn/SmartspacerPlugins/assets/44733677/d11c784c-07a3-4efd-83ce-bcd870032540)

**Comment by k2helix** [comment]
May I ask what app are you using that syncs with Health Connect?

**Comment by ThatOneCalculator** [comment]
Google Fit, but that shouldn't matter for this issue

**Comment by k2helix** [comment]
You're right, I just wanted to know what apps use Health Connect

**Comment by ThatOneCalculator** [comment]
https://health.google/health-connect-android/

https://play.google.com/store/apps/collection/promotion_all__health_connect
