### ISSUE TITLE
[Plugin Request] Outlook Android Mail App

### ISSUE THREAD

**Issue by AsydRayn** [KieronQuinn/SmartspacerPlugins#29]
### App / Plugin Name

Outlook Focused Mail

### URL

Play Store

### Description

Can you do  plugin for outlook mail much in the same way for Gmail. Keep in mind that outlook has a focused mailbox so it only sends notifications when mail goes to that mailbox. All other notifications don't ping, for example newsletter subscriptions and things like that. 

### Where will the plugin get data from?

Notification

### Requirements

- [X] I have read the requirements
- [X] The information I have provided is correct

**Comment by KieronQuinn** [comment]
Added in Notification plugin v1.1

**Comment by AsydRayn** [comment]
Thank you!
