### ISSUE TITLE
[Bug] Cannot log in to Amazon

### ISSUE THREAD

**Issue by Zebov** [KieronQuinn/SmartspacerPlugins#31]
### Select the Plugin you are reporting for

Amazon

### Description

Initially after downloading, the plugin will work as normal. After some time (day perhaps?) it will say it's not logged in. Any attempts at logging in go back to the initial email entry page. The SMS verification code page only lasts for about 5 seconds before reverting back to the email login page. 

The plugin must be deleted, the phone rebooted, and the plugin reinstalled for it to work again.

**Comment by KieronQuinn** [comment]
Forgot to close this, this will have been fixed in the 2.0 Amazon plugin update with the rewrite.
