### ISSUE TITLE
[Feature Request] refresh subscriber count option

### ISSUE THREAD

**Issue by SeanDylan** [KieronQuinn/SmartspacerPlugins#33]
### Select the Plugin you are requesting for

YouTube

### Request

I'm a country ball animator who usually checked subscribers everyday only problem is that if i had a new subscriber this day it doesn't refresh even in a hour it always refreshes everyday so it might be a good idea to have a option like this
This might be just a api issue or it's not possible its understandable if it cannot be refreshed

**Comment by KieronQuinn** [comment]
It already refreshes as often as asked. There is nothing more it can do.

**Comment by SeanDylan** [comment]
> It already refreshes as often as asked. There is nothing more it can do.

Oh
