### ISSUE TITLE
[Bug] maps location not working 

### ISSUE THREAD

**Issue by Dialgatrainer02** [KieronQuinn/SmartspacerPlugins#34]
### Select the Plugin you are reporting for

Google Maps

### Description

I can't grant maps plugin access to location
![Screenshot_20231223-131927](https://github.com/KieronQuinn/SmartspacerPlugins/assets/96637854/0da703dd-f03e-4d9b-8891-f0e8a3f24bf3)

Tapping on the widget does nothing and I can't give it access through settings as it's saying it hasn't asked for any 
I tried giving smart spacer location and it still doesn't work

**Comment by KieronQuinn** [comment]
#9
