### ISSUE TITLE
[Bug] Amazon Plugin always logs out

### ISSUE THREAD

**Issue by dft601** [KieronQuinn/SmartspacerPlugins#36]
### Select the Plugin you are reporting for

Amazon

### Description

Hi,

I can successfully log into Amazon account, but i will be logged out automatically after some minutes. 
So i only get a synchronisation when i do a manually Login again. But this always includes email/ password/ otp
again...
Maybe the OTP is the problem? But  I click on remember the login and also I click on never ask for otp again on this browser.

This concerns Amazon Germany in my case.

Mike

**Comment by KieronQuinn** [comment]
Same issue as #31, it's known and I'm working on a total rewrite of the plugin to counter this (which will be less automatic but unfortunately that's required as it's triggering the bot protection)
