### ISSUE TITLE
[Bug]  Google finance plugin not working

### ISSUE THREAD

**Issue by ReginoDS** [KieronQuinn/SmartspacerPlugins#39]
### Select the Plugin you are reporting for

Google Finance

### Description

The Google finance plugin does not work (P8P with the latest software update). I can try to add it to the list of targets but it never appears on my Homescreen or lock screen. Below is the settings that I'm using (there's no notification of extra permissions needed, either)

![Screenshot_20240104-111957~2](https://github.com/KieronQuinn/SmartspacerPlugins/assets/94646853/f4daddb6-24f2-444a-860a-06535c3202fe)
![Screenshot_20240104-112006~2](https://github.com/KieronQuinn/SmartspacerPlugins/assets/94646853/9a327982-d1b4-4fe9-a555-fca5b9f8cf85)
![Screenshot_20240104-111947](https://github.com/KieronQuinn/SmartspacerPlugins/assets/94646853/0f6c3d5c-029c-4a8b-bce6-4c15263d163d)

**Comment by KieronQuinn** [comment]
Fixed in Google Finance v1.0.2
