### ISSUE TITLE
Weather complication with API key

### ISSUE THREAD

**Issue by redcatxus** [KieronQuinn/SmartspacerPlugins#4]
### App / Plugin Name

Weather complication via API, or something else 

### URL

https://home.openweathermap.org/api_keys

### Description

A weather complication that's, similar to currently available plugins (BBC Weather, Google Weather), which used an open source weather forecast API
an example is going to be on the screenshot below. It will automatically update on certain amount of time, few select option preferred.

![Screenshot_20231029-190351](https://github.com/KieronQuinn/SmartspacerPlugins/assets/137791992/18c065f4-699f-4485-8004-aac62685130d) source: https://play.google.com/store/apps/details?id=twelve.weather.mibrahim

here's where you can get the free API key, as an example: https://home.openweathermap.org/api_keys

### Where will the plugin get data from?

Free API

### Requirements

- [X] I have read the requirements
- [x] The information I have provided is correct

**Comment by ThatOneCalculator** [comment]
+1 on this! I'd love to have a Breezy Weather complication

**Comment by pacjo** [comment]
I think we can close this one, I wrote another plugin, which should be ready for general use: https://github.com/pacjo/SmartspacerPlugins/blob/main/app/src/genericweather/README.md

**Comment by KieronQuinn** [comment]
Agreed
