### ISSUE TITLE
Prayer timings 

### ISSUE THREAD

**Issue by fayyadrc** [KieronQuinn/SmartspacerPlugins#41]
### App / Plugin Name

Islamic prayer timings 

### Description

Shows the timing for the five prayers 

### Where will the plugin get data from?

Free API

### Requirements

- [X] I have read the requirements
- [X] The information I have provided is correct

**Comment by KieronQuinn** [comment]
You have not specified a valid data source, for a free API you must state _which one_ by linking it. Please make a new issue with this.
