### ISSUE TITLE
macrodroid support

### ISSUE THREAD

**Issue by auriafoxgirl** [KieronQuinn/SmartspacerPlugins#42]
### Select the Plugin you are requesting for

Tasker

### Request

As title suggests macrodroid support for tasker plugins. Macrodroid have some tasker support and its possible to select smartspacer tasker plugin but its useless right now because its impossible to make targets and complications from tasker plugin in smartspacer.

**Comment by KieronQuinn** [comment]
Added in Tasker plugin v1.1.1
