### ISSUE TITLE
[Bug] Battery Charging Status target stuck even on unplugged state

### ISSUE THREAD

**Issue by froilaaaaan1** [KieronQuinn/SmartspacerPlugins#46]
### Select the Plugin you are reporting for

Battery

### Description

I encountered this bug on my phone while using this plugin (battery plug-in) where the bug happens in the unplugged state

To describe the bug:
When I plugged in the charger it did update and added the target onto the widget it worked normally such as updating the progress (percent). However, when I unplugged the charger from my phone the complication wouldn't hide or be dismissed. The complication is persistent but once I re-set any settings of the plugin it'll hide right away.

For better demonstration of the bug I will attach a link that will contain the screen record of the bug:
[https://drive.google.com/file/d/1evm2XwlrfyI2FPmhndN6YMT7QiXQEXrW/view?usp=drivesdk](Video Link (Google Drive))

**Comment by KieronQuinn** [comment]
The Battery Plugin is not one of mine, please raise this with the plugin's developer.
