### ISSUE TITLE
Battery plugin does not work

### ISSUE THREAD

**Issue by everypizza1** [KieronQuinn/SmartspacerPlugins#51]
### Select the Plugin you are reporting for

Battery

### Description

The battery plugin seems to require an app not available on the Google Play Store.
Screenshots:
![Screenshot_20240330-075431](https://github.com/KieronQuinn/SmartspacerPlugins/assets/82726593/ef8c0f8c-a467-474d-a2f9-0b79628a485f)
![Screenshot_20240330-075435](https://github.com/KieronQuinn/SmartspacerPlugins/assets/82726593/84b2e4c0-20f6-450d-9bfa-c9a6ae29fa21)

**Comment by KieronQuinn** [comment]
Your device is not compatible with this plugin, it's not a bug.
