### ISSUE TITLE
[Bug] Battery and Energy Monitor plugin not getting installed

### ISSUE THREAD

**Issue by mahesh-yadav-DS** [KieronQuinn/SmartspacerPlugins#54]
### Select the Plugin you are reporting for

Battery

### Description

Unable to install Battery and Energy Monitor plugin not getting installed as when it is redirecting to playstore for companion app then it shows item not found.

**Comment by KieronQuinn** [comment]
Not a bug, your device is not compatible with that plugin. Use the Local Battery plugin instead.

**Comment by mahesh-yadav-DS** [comment]
can you name which companion app it is requesting so that i can try to have a look at it outside playstore?

**Comment by KieronQuinn** [comment]
Don't bother, it only works if the app is pre installed.
