### ISSUE TITLE
[Feature Request] Handle multiple device in Controls plugin

### ISSUE THREAD

**Issue by pogman-code** [KieronQuinn/SmartspacerPlugins#60]
### Select the Plugin you are requesting for

Controls

### Request

I would be nice to be able to handle more than one device in a Target/Complication.  
The usecase would be to turn on/off multiple lights at once or open/close multiple blinds, etc.

I am sure this is easier said than done so I would understand if it is not possible to implement.

**Comment by KieronQuinn** [comment]
This isn't something the Controls API supports unfortunately, and I don't think stressing it more by sending multiple action requests at once is a good idea with how sensitive and unstable it is

**Comment by pogman-code** [comment]
I understand, no problem.
A workaround would be to be able to run actions using google assistant API (similar to what Action Blocks do)

https://developers.google.com/assistant
https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.maui.actionblocks

Does that sound plausible?

**Comment by KieronQuinn** [comment]
AFAIK there's no API, but I have considered making an Action Blocks plugin which loads & clicks the widget
