### ISSUE TITLE
[Bug] Battery Device Icon looks low quality/blurry

### ISSUE THREAD

**Issue by FineFindus** [KieronQuinn/SmartspacerPlugins#64]
### Select the Plugin you are reporting for

Battery

### Description

The icon used for Headphones looks blurry (it is more pronounced when viewed on a real device).
![Blurry Headphones Icon](https://github.com/user-attachments/assets/13ecc43a-b083-4ab6-8ea3-82cd0cddd5b9)

For comparison, the Digital Wellbeing icon is rendered sharp
![Digital wellbeing Icon being rendered sharp](https://github.com/user-attachments/assets/cf5c1dcf-73cf-44ac-ae50-40d2de1d0fc8)

Since I suspect that the icon is provided by the OS, maybe they could be mapped to a higher quality version?

Using a Pixel 7a, Android 14 with Niagara Launcher.

**Comment by KieronQuinn** [comment]
The icons do indeed come from the widget source, unfortunately mapping images is difficult and quite CPU intensive for something which changes often like battery percentages, so this won't be possible.
