### ISSUE TITLE
[Plugin Request] Breezy Weather for weather

### ISSUE THREAD

**Issue by Xenoslyce** [KieronQuinn/SmartspacerPlugins#65]
### App / Plugin Name

Breezy Weather

### URL

https://github.com/breezy-weather/breezy-weather

### Description

Use Breezy Weather as a weather provider. Getting weather data from a notification could work, but Breezy Weather has support for sharing weather data to Gadgetbridge without one, so a similar setup may be possible with cooperation with the other project.

### Where will the plugin get data from?

Notification, Other (please specify in the description)

### Requirements

- [X] I have read the requirements
- [X] The information I have provided is correct

**Comment by KieronQuinn** [comment]
If it works with Gadgetbridge already, does the Generic Weather plugin from the repository not work?

**Comment by KieronQuinn** [comment]
Had it confirmed elsewhere that Breezy Weather is a supported provider for the Generic Weather Plugin. If you have any requests for that plugin regarding Breezy, please make them on its repository.

Closing as already available.
