### ISSUE TITLE
Playback [Feature Request] 

### ISSUE THREAD

**Issue by adnan6194** [KieronQuinn/SmartspacerPlugins#7]
### Select the Plugin you are requesting for

YouTube

### Request

Sorry for choosing anything above but it's not there. I mean the Music Widget which appears when playing YT for example. There should be a playback (start/stop), forward and previous video button. Would be really helpful.

**Comment by KieronQuinn** [comment]
Not possible in Smartspace itself, hence why the widget appears below it in Expanded Smartspace.
