### ISSUE TITLE
Duolingo progress plugin

### ISSUE THREAD

**Issue by Mr-Pixel-Perfect** [KieronQuinn/SmartspacerPlugins#8]
### App / Plugin Name

Duolingo

### URL

https://play.google.com/store/apps/details?id=com.duolingo

### Description

This plugin adds a target.
The plugin would cycle between a few sentences and it would correspond with wether you did your lesson or not. The sentences would be similar or the same ones from the reminders the app sends.

Sentence examples:

Didn't do lesson:
1.Let's practice!
2.Time to practice!
3.PRACTICE NOW!

Did do lesson:
1.You did it!
2.Great job!
3.Streak saved!

Images example:
![Untitled35_20231103192658](https://github.com/KieronQuinn/SmartspacerPlugins/assets/147725721/1222a114-6eda-43aa-bc47-4cdec1c14d4e)
![Untitled35_20231103193424](https://github.com/KieronQuinn/SmartspacerPlugins/assets/147725721/fc26c4c3-cae9-47b7-9de4-6b47e0908466)

### Where will the plugin get data from?

Widget

### Requirements

- [X] I have read the requirements
- [X] The information I have provided is correct

**Comment by pacjo** [comment]
Can you try this: [app-duolingo-debug.apk.zip](https://github.com/KieronQuinn/SmartspacerPlugins/files/13816479/app-duolingo-debug.apk.zip)

There's one small bug, where not all background elements are stretched, but it's hard to spot. I'll fix it later. Everything else should work fine.

**Comment by pacjo** [comment]
Ok, it's on the official repository now ([#28](https://github.com/KieronQuinn/SmartspacerPluginRepository/issues/28)), this can probably be closed now.
